modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: SimApp
      pre_blockers: [ upgrade ]
      begin_blockers: [ staking ]
      end_blockers: [ staking ]
      init_genesis: [ auth, bank, staking, genutil, upgrade, authority ]
      override_store_keys:
        - module_name: auth
          kv_store_key: acc
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: noble
      module_account_permissions:
        - account: fee_collector
        - account: bonded_tokens_pool
          permissions: [ burner, staking ]
        - account: not_bonded_tokens_pool
          permissions: [ burner, staking ]
      authority: authority # Utilize our custom x/authority module.
  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
      blocked_module_accounts_override:
        [ auth, distribution, bonded_tokens_pool, not_bonded_tokens_pool ]
      authority: authority # Utilize our custom x/authority module.
  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module
      authority: authority # Utilize our custom x/authority module.
  - name: genutil
    config:
      "@type": cosmos.genutil.module.v1.Module
  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module
      authority: authority # Utilize our custom x/authority module.
  - name: tx
    config:
      "@type": cosmos.tx.config.v1.Config
  - name: upgrade
    config:
      "@type": cosmos.upgrade.module.v1.Module
      authority: authority # Utilize our custom x/authority module.

  - name: authority
    config:
      "@type": noble.authority.module.v1.Module
